version: '3'

services:
  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASS=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo

  app:
    build: .
    command: yarn migrate
    depends_on:
      - postgres
    ports:
      - '3333:3333'
    environment:
      - DB_HOST=postgres
      - MONGO_HOST=mongo
    volumes:
      - .:/usr/app

volumes:
  postgres_data:
